---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
spec:
  type: ClusterIP
  ports:
  - name: {{ name }}
    port: {{ port }}
    protocol: TCP
    targetPort: {{ port }}
  selector:
    app: {{ name }}
